name: Build and Deploy Site

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Environment variables for all steps
    env:
      HUGO_BUILD_FOLDER: out
      S3_BUCKET_URI: s3://jerryryle.com
      CLOUDFRONT_DISTRIBUTION_ID: E1DWOMWZ44RVNH

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0   # This gets all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Setup Tidy
        run: sudo apt-get install tidy

      - name: Hugo Build
        run: ./gen

      - name: Tidy HTML
        run: ./tidy

      - name: Archive Generated Site
        uses: actions/upload-artifact@v4
        with:
          name: generated-site
          path: ${{ env.HUGO_BUILD_FOLDER }}

      - name: Configure AWS credentials from publish account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PUBLISH_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PUBLISH_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Sync to S3
        run: aws s3 sync --delete --no-follow-symlinks --exclude "*.DS_Store" "${{ env.HUGO_BUILD_FOLDER }}" ${{ env.S3_BUCKET_URI }}

      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
